spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
    hidden method:
      filter:
        enabled: true  #  open REST

  datasource:
    url: jdbc:mysql://localhost:3306/data_backup
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 

  servlet:
    multipart:
      max-file-size: 50MB

mybatis-plus:
  type-aliases-package: com.example.music.player.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    db-config:
      id-type: auto

server:
  port: 8888
  connection-timeout: 80000
  disableUploadTimeout: false
